server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/idevbn/ead-config-server-repo
          default-label: main
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost